- name: Generate keystore (ONE TIME ONLY)
  run: |
    keytool -genkeypair -v -keystore uranium-release.jks \
      -keyalg RSA -keysize 2048 -validity 10000 -alias uranium \
      -storepass "@di20june09" -keypass "@di20june09" \
      -dname "CN=Uranium, OU=Dev, O=Uranium, L=City, S=State, C=IN"

- name: Upload keystore
  uses: actions/upload-artifact@v4
  with:
    name: uranium-keystore
    path: uranium-release.jks
